### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter

### ISSUE THREAD

**Issue by henricook** [addshore/facebook-data-image-exif#26]
Hi all,

I was really excited to find this project, it's great that it exists!

I'm running on Ubuntu Linux with Java 17 (or 21) I've tried both and JavaFX 17.0.12 (I've also tried 22.x)

When I run the app from the command line I get an error about paintconverter not being found - full stack trace below. Does anyone have any wisdom to share to get around this please? 🙏🏻 

```
#java --module-path /home/henri/src/openjfx-17.0.12_linux-x64_bin-sdk/javafx-sdk-17.0.12/lib --add-modules javafx.controls,javafx.fxml,javafx.graphics -jar /home/henri/Downloads/facebook-data-image-exif.jar

Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1082)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javafx.fxml.LoadException: 
file:/home/henri/Downloads/facebook-data-image-exif.jar!/com/github/addshore/facebook/data/image/exif/dataEntry.fxml:41

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2714)
	at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1022)
	at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:757)
	at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3368)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3324)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3292)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3264)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3240)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:3233)
	at com.github.addshore.facebook.data.image.exif.MainView.<init>(MainView.java:39)
	at com.github.addshore.facebook.data.image.exif.Main.getDataEntryScene(Main.java:95)
	at com.github.addshore.facebook.data.image.exif.Main.start(Main.java:45)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1020)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter
	at com.jfoenix.controls.JFXTextField$StyleableProperties.<clinit>(JFXTextField.java:241)
	at com.jfoenix.controls.JFXTextField.<init>(JFXTextField.java:146)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.PaintConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 30 more
Exception running application com.github.addshore.facebook.data.image.exif.Main

```

**Comment by henricook** [comment]
I eventually got this working, I had the same problem on Windows too.

Fixing this on Linux I first installed a version of Java 11 with FX bundled, I did this with SDKMAN! and it meant I didn't have to worry so much about making sure my FX and Java versions aligned.

`.sdkmanrc`:

```
java=11.0.24.fx-zulu
```

Either I had something unique wrong, or the paths in the Facebook export have changed slightly. There was also some issues with getString vs. getInt for creation timestamps. Those minor changes are in the attached diff (txt so that github lets me upload it).

[changes.patch.txt](https://github.com/user-attachments/files/16467497/changes.patch.txt)

Then I built and ran the app from source with `mvn clean package && java -jar target/facebook-data-image-exif-jar-with-dependencies.jar`
