### ISSUE TITLE
Getting error on mac

### ISSUE THREAD

**Issue by jitendravyas** [addshore/facebook-data-image-exif#6]
![image](https://user-images.githubusercontent.com/77309/56630654-bc6a5900-666f-11e9-9d61-e5ea560e2040.png)

**Comment by addshore** [comment]
Sorry for a slow reply here, apparently I havn't been stalking this repo.

I have no idea what is causing that issue, what OS version are you running?
I don't have a mac myself to try this out on, but I know it has worked for some other people.

**Comment by mpatfield** [comment]
Excited to try this out but am unfortunately experiencing the same problem. I'm on macOS Catalina 10.15.1 and I tried looking in the system console as the error message suggests, but didn't see anything obvious.

Happy to help debug if there's anything you want me to try.

**Comment by addshore** [comment]
I have no idea how to debug this on a mac, all I can hope is that someone manages to find a more verbose / system level / java log message somewhere that gives us a hint!

**Comment by mpatfield** [comment]
There is a bit more info if you run the jar directly from the terminal:

```
mpatfield$ java -jar facebook-data-image-exif.jar 
Error: Could not find or load main class com.github.addshore.facebook.data.image.exif.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by ChimeraCoder** [comment]
It's not just on a Mac: I get the same error when running under Ubuntu 20.04 (Focal):

```
Error: Could not find or load main class com.github.addshore.facebook.data.image.exif.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
Error: Could not find or load main class com.github.addshore.facebook.data.image.exif.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by pbcornelius** [comment]
It was build with Java 8 and needs Java 8 to run. Since Java 9, `com.sun.javafx.css.converters.PaintConverter` doesn't exist anymore.

**Comment by addshore** [comment]
As of a few days ago this is now built with JDK 11
https://github.com/addshore/facebook-data-image-exif/commit/550761f4c98405b6b97b68fe07e7b1d0e193e206
which sounds like perhaps this would be fixed with a new build? https://stackoverflow.com/questions/46754639/javafx-weird-classnotfoundexception-after-updating-to-java-9#46756098

You can give this a go at https://github.com/addshore/facebook-data-image-exif/releases/tag/0.11-alpha1

**Comment by pbcornelius** [comment]
Thanks for the quick response. I made it work yesterday with Java 8 and have processed all my Facebook pictures.

Since JDK11, JavaFX is not part of the default JRE anymore. It needs to be downloaded separately and the run command needs to include something like `--module-path {PATH_TO_FX} --add-modules=javafx.controls`. `{PATH_TO_FX}` will be different on different machines.

JavaFX supports building self-contained runnables that include all libraries. Might be worth setting up once and then it'll run for years.

Great tool btw, thanks a lot for creating it!

**Comment by addshore** [comment]
on master now javafx is fetched from maven and bundled with the build jar.
So, fingers crossed that jar linked above should work out of the box for you and other people in this situation!

**Comment by merttoka** [comment]
The same issue happens on Windows 10 as well with JDK-11.0.10.9. I tried both 0.1 and 0.11 versions.

```
PS C:\Users\<user>\Desktop\facebook photos> java.exe --module-path .\facebook-data-image-exif\javafx-sdk-11.0.2\lib --add-modules javafx.controls -jar .\facebook-data-image-exif.jar
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessError: class com.sun.javafx.fxml.FXMLLoaderHelper (in unnamed module @0x5925857d) cannot access class com.sun.javafx.util.Utils (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.util to unnamed module @0x5925857d
        at com.sun.javafx.fxml.FXMLLoaderHelper.<clinit>(FXMLLoaderHelper.java:38)
        at javafx.fxml.FXMLLoader.<clinit>(FXMLLoader.java:2056)
        at com.github.addshore.facebook.data.image.exif.MainView.<init>(MainView.java:39)
        at com.github.addshore.facebook.data.image.exif.Main.getDataEntryScene(Main.java:94)
        at com.github.addshore.facebook.data.image.exif.Main.start(Main.java:44)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Exception running application com.github.addshore.facebook.data.image.exif.Main
```

**Comment by ChrisChiera** [comment]
On Apple Silicon Mac, ran and it opened but anytime clicked Browse for either of the browser buttons in the GUI it would just spin endlessly and freeze. I then read that it needs Java 11 instead of the the Java 8 that is on the latest Macs. I'm on Ventura Beta. I installed Java 11 here https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html  Arm 64 DMG Installer and all appears to have gone smoothly. I get the java file could not launch to checked console error, or sometimes nothing happens when clicking it. But has not been able to run since updating from Java 8 to 11 on Mac. Any thoughts? Or does all this JavaFX additional commands noted in this thread still required even on a Mac and using the latest addshore code?

**Comment by davidtsui1** [comment]
For anyone stumbling on this post in the future, if you are using macOS, this utility will freeze if you click on the "Browse" button in the GUI. @TechRemarker's suggestion to paste in the pathnames for both the Facebook export and exiftool locations is still a valid workaround as of July 2025.

Also use the following fork, as Facebook changed some of the folder names used within the export. https://github.com/TanJunHong/facebook-data-image-exif/tree/master

**Comment by addshore** [comment]
> For anyone stumbling on this post in the future, if you are using macOS, this utility will freeze if you click on the "Browse" button in the GUI. [@TechRemarker](https://github.com/TechRemarker)'s suggestion to paste in the pathnames for both the Facebook export and exiftool locations is still a valid workaround as of July 2025.

❤️

> Also use the following fork, as Facebook changed some of the folder names used within the export. https://github.com/TanJunHong/facebook-data-image-exif/tree/master

I also just added this as a note in the README! :)

https://github.com/addshore/facebook-data-image-exif/commit/462f555691970e98076d72be52414a6914a1185c

**Comment by addshore** [comment]
I'd be up for taking another look at this tool at some point and rewriting it in something other than Java.
And maybe making it compatible with both older and newer dump formats!
